package com.example.hackernews.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "Posts")
public class Content {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    private String contentId;
    @DynamoDBAttribute
    private String content;
}
